# Generated by Django 4.0 on 2021-12-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campusName', models.CharField(max_length=64, unique=True, verbose_name='campus_name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('lastname', models.CharField(max_length=200, verbose_name='last_name')),
                ('firstname', models.CharField(max_length=200, verbose_name='first_name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('moderator', models.BooleanField(max_length=200, verbose_name='is_moderator')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('à vendre', 'Tosell'), ('à donner', 'Togive')], max_length=64)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=2048, verbose_name='description')),
                ('state', models.CharField(choices=[('publié', 'Published'), ('attendre validation', 'Pending'), ('refusé', 'Rejected'), ('clôturé', 'Closed')], default='attendre validation', max_length=64)),
                ('price', models.IntegerField(verbose_name='price')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.user')),
            ],
        ),
    ]
