# Generated by Django 4.0 on 2021-12-14 12:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('à vendre', 'Tosell'), ('à donner', 'Togive')], max_length=64)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=2048, verbose_name='description')),
                ('state', models.CharField(choices=[('publié', 'Published'), ('attendre validation', 'Pending'), ('refusé', 'Rejected'), ('clôturé', 'Closed')], default='attendre validation', max_length=64)),
                ('price', models.IntegerField(default=0, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='campus_id')),
                ('campusName', models.CharField(max_length=64, unique=True, verbose_name='campus_name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='category_id')),
                ('categoryName', models.CharField(max_length=64, unique=True, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='location_id')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('lastname', models.CharField(max_length=200, verbose_name='last_name')),
                ('firstname', models.CharField(max_length=200, verbose_name='first_name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('moderator', models.BooleanField(default=False, max_length=200, verbose_name='is_moderator')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='media_id')),
                ('url', models.TextField(verbose_name='url')),
                ('ad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdsCampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.ad')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.campus')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.location')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.user'),
        ),
    ]
