# Generated by Django 4.0 on 2021-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('lastname', models.CharField(max_length=200, verbose_name='last_name')),
                ('firstname', models.CharField(max_length=200, verbose_name='first_name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('moderator', models.BooleanField(max_length=200, verbose_name='moderator')),
                ('campus', models.IntegerField(default=1, verbose_name='campus_id')),
            ],
        ),
    ]
