# Generated by Django 4.0 on 2021-12-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PFE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PFE.category'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.TextField(verbose_name='url'),
        ),
    ]
